#variables:
#  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#
#services:
#  - docker:dind
#
#stages:
#  - build
#  - test
#  - sonarqube
#
#build:
#  stage: build
#  script:
#    - docker build -t rivaproject-backend .
#
#test:
#  stage: test
#  script:
#    - docker run -e GRADLE_OPTS="$GRADLE_OPTS" rivaproject-backend ./gradlew test
#
#sonarqube:
#  stage: sonarqube
#  script:
#    - docker run -e GRADLE_OPTS="$GRADLE_OPTS" rivaproject-backend ./gradlew sonar
#  allow_failure: true
#

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

sonarqube:
  stage: sonarqube
  script:
    - ./gradlew sonar
  allow_failure: true

#deploy_dev:
#  stage: deploy_dev
#  script:
#    - docker build -t rivaproject-backend:dev .
#    - docker run -d -p 8080:8080 --name=riva-backend-dev rivaproject-backend:dev

deploy:
  stage: deploy
  script:
    -  ./gradlew clean assemble
    - docker build -t rivaproject-backend .
    - docker stop riva-backend-staging
    - docker rm riva-backend-staging
    - docker run -d -p 8080:8080 --net=docker_riva_network_staging --env spring_profiles_active=staging --name=riva-backend-staging rivaproject-backend
